# Generated by Django 5.0.1 on 2024-02-04 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('lectures', '0015_alter_subtopicslecturecontain_title'),
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grades_question', models.IntegerField()),
                ('question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grades', models.IntegerField()),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('lecture_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lectures.lecture')),
                ('quiz_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('subtopic_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lectures.subtopicslecturecontain')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question_grades', models.ManyToManyField(blank=True, to='grades.questiongrade')),
            ],
        ),
        migrations.CreateModel(
            name='TotalGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_grades', models.IntegerField()),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
