# Generated by Django 5.0.1 on 2024-02-04 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='grades',
        ),
    ]
