# Generated by Django 5.0.1 on 2024-02-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_remove_grades_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalgrades',
            name='total_grades',
            field=models.IntegerField(default=0),
        ),
    ]
