# Generated by Django 5.0.1 on 2024-01-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
