# Generated by Django 5.0.1 on 2024-01-28 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('department', models.CharField(max_length=2, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('0', 'Inactive'), ('1', 'Active')], default='0', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course_semester', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], default='Spring', max_length=10)),
                ('languages', models.CharField(choices=[('English', 'English'), ('Turkish', 'Turkish')], default='English', max_length=10)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
