# Generated by Django 5.0.1 on 2024-01-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_remove_lecture_titles_lecture_subtopics1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='subtopics1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subtopics10',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subtopics11',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subtopics12',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subtopics13',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subtopics14',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subtopics2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subtopics3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subtopics4',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subtopics5',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subtopics6',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subtopics7',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subtopics8',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subtopics9',
            field=models.CharField(max_length=50),
        ),
    ]
