# Generated by Django 5.0.1 on 2024-01-31 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0005_subtopicslecturecontain'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='-', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='subtopicslecturecontain',
            old_name='lecture',
            new_name='lecture_id',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='subtopics1',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='subtopics10',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='subtopics11',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='subtopics12',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='subtopics13',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='subtopics14',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='subtopics2',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='subtopics3',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='subtopics4',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='subtopics5',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='subtopics6',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='subtopics7',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='subtopics8',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='subtopics9',
        ),
        migrations.AddField(
            model_name='lecture',
            name='titles',
            field=models.ManyToManyField(to='lectures.lessontitle'),
        ),
        migrations.AddField(
            model_name='subtopicslecturecontain',
            name='lesson_title_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='lectures.lessontitle'),
        ),
    ]
