# Generated by Django 5.0.1 on 2024-01-31 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0007_alter_subtopicslecturecontain_lesson_title_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessonTitle',
            new_name='lectures_lessontitle',
        ),
    ]
