# Generated by Django 5.0.1 on 2024-01-31 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0009_rename_lectures_lessontitle_lessontitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='titles',
            field=models.ManyToManyField(default='0', to='lectures.lessontitle'),
        ),
        migrations.AlterField(
            model_name='subtopicslecturecontain',
            name='lesson_title_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='lectures.lessontitle'),
        ),
    ]
