# Generated by Django 5.0.1 on 2024-01-31 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0010_alter_lecture_titles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopicslecturecontain',
            name='lecture_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lectures.lecture'),
        ),
        migrations.AlterField(
            model_name='subtopicslecturecontain',
            name='lesson_title_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lectures.lessontitle'),
        ),
    ]
