# Generated by Django 5.0.1 on 2024-01-31 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0011_alter_subtopicslecturecontain_lecture_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='titles',
            field=models.ManyToManyField(to='lectures.lessontitle'),
        ),
        migrations.AlterField(
            model_name='lessontitle',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subtopicslecturecontain',
            name='lecture_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectures.lecture'),
        ),
        migrations.AlterField(
            model_name='subtopicslecturecontain',
            name='lesson_title_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectures.lessontitle'),
        ),
    ]
