# Generated by Django 5.0.1 on 2024-01-31 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0013_rename_lesson_title_id_subtopicslecturecontain_lesson_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopicslecturecontain',
            name='lesson_title',
        ),
    ]
