# Generated by Django 5.0.1 on 2024-01-31 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0014_remove_subtopicslecturecontain_lesson_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopicslecturecontain',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectures.lessontitle'),
        ),
    ]
